#!/bin/bash

clear
git checkout dev
git status
echo Press Enter to continue ..
read

git rebase master
git checkout master
git status
git merge dev
git push origin master
git push origin dev
git checkout dev
