#!/bin/bash

clear
git fetch
git remote update
git checkout dev
git status

echo Press Enter to continue ..
read

git pull origin dev
git checkout master
git status
echo Press Enter to continue ..
read

git pull origin master
git checkout dev

